// <auto-generated />
using Chefs_N_Dishes.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Chefs_N_Dishes.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20200421234901_ChefsNDishesSecondMigration")]
    partial class ChefsNDishesSecondMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Chefs_N_Dishes.Models.Chefs", b =>
                {
                    b.Property<int>("Chef_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Chef_Age");

                    b.Property<string>("Chef_FirstName");

                    b.Property<string>("Chef_LastName");

                    b.HasKey("Chef_ID");

                    b.ToTable("chefs");
                });

            modelBuilder.Entity("Chefs_N_Dishes.Models.Dishes", b =>
                {
                    b.Property<int>("Food_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Calories");

                    b.Property<int>("Chef_ID");

                    b.Property<string>("Description");

                    b.Property<string>("Food_Name");

                    b.Property<int>("Tastiness");

                    b.HasKey("Food_ID");

                    b.HasIndex("Chef_ID");

                    b.ToTable("dishes");
                });

            modelBuilder.Entity("Chefs_N_Dishes.Models.Dishes", b =>
                {
                    b.HasOne("Chefs_N_Dishes.Models.Chefs", "Creator")
                        .WithMany("CreatedDishes")
                        .HasForeignKey("Chef_ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
